### ISSUE TITLE
could not find machine-id file

### ISSUE THREAD

**Issue by KELiON** [davidwood/machine-id#1]
I use machine-id in my electron app and one of users [reported](https://github.com/KELiON/cerebro/issues/41) this bug: 

> Just installed cerebro on Arch Linux and this happened:
```
cat: /var/lib/dbus/machine-id: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: cat /var/lib/dbus/machine-id
cat: /var/lib/dbus/machine-id: No such file or directory

    at checkExecSyncError (child_process.js:495:13)
    at execSync (child_process.js:535:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at c (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:309:7107)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:283:100)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:159:20)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:52:22)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
```

> I solved it by creating a sym link to the file that actually was located at `/etc/machine-id` instead of `/var/lib/dbus/machine-id`

**Comment by davidwood** [comment]
This module generates a machine ID from hardware properties, but does not read the machine ID from the file system. I'll comment on your issue on Cerebro, but this is the wrong `machine-id` project.
